import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
const base='http://localhost:8091';
function cli(file,...args){const r=spawnSync('docker',['compose','--env-file','local/.env','-f','local/compose.yml','run','--rm','cli','wp','eval-file',`/fwf-tests/${file}`,...args.map(String)],{encoding:'utf8'});if(r.status!==0)throw new Error('Fixture operation failed (credential output suppressed)');return r.stdout.trim();}
const fixtures=JSON.parse(cli('create-admin.php'));
const content=JSON.parse(cli('content-fixture.php','create'));
cli('builder-fixture.php','snapshot');
function session(){
 const cookies=new Map();
 return async (path,params={})=>{
   const r=await fetch(base+path,{...params,redirect:'manual',headers:{...params.headers,'Connection':'close','Cookie':[...cookies].map(([k,v])=>`${k}=${v}`).join('; ')}});
   for(const header of r.headers.getSetCookie()){const part=header.split(';')[0];const index=part.indexOf('=');cookies.set(part.slice(0,index),part.slice(index+1));}
   return {status:r.status,location:r.headers.get('location'),body:await r.text()};
 };
}
let checks=0;const ok=(x,label)=>{assert(x,label);checks++;console.log('PASS:',label);};
async function login(actor){const s=session();await s('/wp-login.php');const r=await s('/wp-login.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({log:actor.login,pwd:actor.password,'wp-submit':'Log In',testcookie:'1',redirect_to:base+'/wp-admin/'})});ok(r.status===302,'local fixture login');return s;}
try{
 const admin=await login(fixtures.administrator);
 const screens=['','-content','-identity','-design','-modules','-connections','-ai','-updates','-maintenance','-audit'];
 for(const screen of screens){const r=await admin('/wp-admin/admin.php?page=falcon-wf'+screen);ok(r.status===200 && r.body.includes('class="wrap fwf"') && !r.body.includes('Fatal error'),'admin screen '+(screen||'overview')+' renders');}
 const design=await admin('/wp-admin/admin.php?page=falcon-wf-design');
 ok(design.body.includes('name="reset_design" value="yes" formnovalidate'),'design reset control submits explicit intent without HTML field validation');
 const designForm={action:'fwf_action',operation:'save_design',screen:'design',theme:design.body.match(/name="theme" value="([^"]+)"/)?.[1],revision:design.body.match(/name="revision" value="([^"]+)"/)?.[1],_wpnonce:design.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1],'design[ink]':'#123456','design[body_font]':'system','design[h1]':'64'};
 let designResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(designForm)});
 const savedDesign=await admin('/wp-admin/admin.php?page=falcon-wf-design');
 ok(designResult.status===302 && savedDesign.body.includes('value="#123456"'),'design admin form persists settings');
 const designHTML=await (await fetch(base+'/',{headers:{Connection:'close'}})).text();
 ok(designHTML.includes('--fwf-ink:#123456;') && designHTML.includes('--fwf-h1:64px;'),'saved design reaches actual parent frontend inline CSS');
 designResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...designForm,'design[ink]':'#654321'})});
 const staleDesign=await admin('/wp-admin/admin.php?page=falcon-wf-design');
 ok(designResult.status===302 && staleDesign.body.includes('Desain sudah berubah') && staleDesign.body.includes('value="#123456"'),'stale design HTTP form preserves latest settings');
 const freshDesign={...designForm,revision:staleDesign.body.match(/name="revision" value="([^"]+)"/)?.[1]};
 designResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...freshDesign,'design[ink]':'</style><script>bad</script>'})});
 const badDesign=await admin('/wp-admin/admin.php?page=falcon-wf-design');
 ok(designResult.status===302 && badDesign.body.includes('Nilai tidak valid') && badDesign.body.includes('value="#123456"'),'unsafe CSS input rejected without partial write');
 designResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...freshDesign,_wpnonce:'invalid'})});
 ok(designResult.status===403,'design mutation requires valid nonce');
 const resetDesign={...freshDesign};for(const key of Object.keys(resetDesign)){if(key.startsWith('design['))resetDesign[key]='';}
 designResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...resetDesign,reset_design:'yes'})});
 ok(designResult.status===302 && !(await (await fetch(base+'/',{headers:{Connection:'close'}})).text()).includes('--fwf-ink:#123456;'),'reset design button removes frontend overrides');
 const connections=await admin('/wp-admin/admin.php?page=falcon-wf-connections');
 ok(connections.body.includes('name="release_tag"') && connections.body.includes('local/staging') && !connections.body.match(/<input[^>]*name="release_tag"[^>]*required/),'release connection explains and renders pinned prerelease field');
 const repoNonce=connections.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];
 let connectionResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'save_repo',screen:'connections',repo:'fixture/falcon-wf',release_tag:'v0.1.0-alpha.3',_wpnonce:repoNonce})});
 const pinned=await admin('/wp-admin/admin.php?page=falcon-wf-connections');
 ok(connectionResult.status===302 && pinned.body.includes('value="v0.1.0-alpha.3"'),'nonce-protected connection saves selected prerelease tag');
 connectionResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'save_repo',screen:'connections',repo:'fixture/falcon-wf',release_tag:'../unsafe',_wpnonce:repoNonce})});
 const rejected=await admin('/wp-admin/admin.php?page=falcon-wf-connections');
 ok(connectionResult.status===302 && rejected.body.includes('value="v0.1.0-alpha.3"'),'invalid release selection preserves previous connection');
 const projectNonce=rejected.body.match(/name="operation" value="save_project"[\s\S]*?name="_wpnonce" value="([^"]+)"/)?.[1];
 const projectForm={action:'fwf_action',operation:'save_project',screen:'connections',project_repo:'fixture/client-design',project_id:'falcon-reference',theme_id:'falcon-reference',project_tag:'v0.1.0-alpha.2',_wpnonce:projectNonce};
 let projectResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(projectForm)});
 const projectConnection=await admin('/wp-admin/admin.php?page=falcon-wf-connections');
 ok(projectResult.status===302 && projectConnection.body.includes('value="fixture/client-design"') && projectConnection.body.includes('FWF_PROJECT_GITHUB_TOKEN'),'project connection form stores isolated repo and explains server-side token');
 projectResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...projectForm,theme_id:'falcon-theme'})});
 const projectRefused=await admin('/wp-admin/admin.php?page=falcon-wf-connections');
 ok(projectResult.status===302 && projectRefused.body.includes('value="falcon-reference"'),'project form cannot retarget core theme');
 const projectUpdates=await admin('/wp-admin/admin.php?page=falcon-wf-updates');
 ok(projectUpdates.body.includes('Paket desain proyek') && projectUpdates.body.includes('Periksa paket proyek'),'project check/review flow appears in updates');
 for(const operation of ['save_project','check_project','apply_project','disconnect_project']){
  projectResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...projectForm,operation,_wpnonce:'invalid'})});
  ok(projectResult.status===403,`project ${operation} requires its own nonce`);
 }
 const disconnectNonce=projectConnection.body.match(/name="operation" value="disconnect_project"[\s\S]*?name="_wpnonce" value="([^"]+)"/)?.[1];
 projectResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'disconnect_project',screen:'connections',_wpnonce:disconnectNonce})});
 ok(projectResult.status===302 && !(await admin('/wp-admin/admin.php?page=falcon-wf-connections')).body.includes('value="fixture/client-design"'),'project disconnect removes connection');
 const identity=await admin('/wp-admin/admin.php?page=falcon-wf-identity');
 const seoNonce=identity.body.match(/name="operation" value="save_seo"[\s\S]*?name="_wpnonce" value="([^"]+)"/)?.[1];
 const seoRevision=identity.body.match(/name="revision" value="([^"]+)"/)?.[1];
 const seoForm={action:'fwf_action',operation:'save_seo',screen:'identity',seo_mode:'falcon',revision:seoRevision,_wpnonce:seoNonce};
 ok(!!seoNonce && identity.body.includes('name="seo_mode"'),'SEO form has dedicated nonce and explicit owner selection');
 let seoResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...seoForm,_wpnonce:'invalid'})});
 ok(seoResult.status===403,'SEO mutation requires dedicated nonce');
 seoResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(seoForm)});
 const seoSaved=await admin('/wp-admin/admin.php?page=falcon-wf-identity');
 ok(seoResult.status===302 && /value="falcon"\s+selected/.test(seoSaved.body),'SEO opt-in saves through actual admin boundary');
 const seoHome=await (await fetch(base+'/',{headers:{Connection:'close'}})).text();
 ok(seoHome.includes('noindex') && !seoHome.includes('property="og:title"'),'coming-soon remains noindex without Falcon metadata after opt-in');
 seoResult=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...seoForm,seo_mode:'external',revision:seoSaved.body.match(/name="revision" value="([^"]+)"/)?.[1]})});
 ok(seoResult.status===302,'SEO metadata can be disabled from admin');
 const nonce=identity.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];ok(!!nonce,'identity action uses nonce');
 let r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'save_identity',screen:'identity',name:'Falcon WF Local',contact:'',_wpnonce:nonce})});
 ok(r.status===302 && r.location.includes('falcon-wf-identity'),'authorized identity action redirects to screen');
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'save_identity',name:'Bad'})});ok(r.status===403,'missing nonce refused');
 const editor=await login(fixtures.editor);
 const seoDenied=await editor('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(seoForm)});ok(seoDenied.status===403,'editor cannot change SEO owner');
 r=await editor('/wp-admin/admin.php?page=falcon-wf-design');ok(r.status===403,'editor cannot open design settings');
 r=await editor('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(designForm)});ok(r.status===403,'editor direct design mutation denied');
 for(const operation of ['save_project','check_project','apply_project','disconnect_project']){r=await editor('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...projectForm,operation})});ok(r.status===403,`editor project ${operation} denied`);}
 r=await editor('/wp-admin/admin.php?page=falcon-wf-content');ok(r.status===403,'editor cannot change content definitions');
 r=await editor('/wp-admin/admin.php?page=falcon-wf-ai');ok(r.status===403,'editor cannot open AI policy page directly');
 r=await editor('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_action',operation:'install_theme',_wpnonce:nonce})});ok(r.status===403,'editor direct install action refused');
 r=await admin('/wp-admin/admin.php?page=falcon-wf-ai');ok(!r.body.includes(fixtures.administrator.password),'no fixture credential in HTML');
 const formPath='/wp-admin/post.php?post='+content.id+'&action=edit';
 const form=await editor(formPath);
 ok(form.status===200 && form.body.includes('fwf_fields_nonce') && form.body.includes('name="fields[project_stage]"'),'custom fields render on native content editor');
 const nativeNonce=form.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];
 const metaNonce=form.body.match(/name="fwf_fields_nonce" value="([^"]+)"/)?.[1];
 const metaRevision=form.body.match(/name="fwf_meta_revision" value="([^"]+)"/)?.[1];
 const contentRevision=form.body.match(/name="fwf_content_revision" value="([^"]+)"/)?.[1];
 const nativeValues={action:'editpost',post_ID:String(content.id),post_type:'fwf_project',post_title:content.fields.title,post_status:'draft',_wpnonce:nativeNonce,fwf_fields_nonce:metaNonce,fwf_meta_revision:metaRevision,fwf_content_revision:contentRevision,'fields[location]':'Native HTTP changed','fields[project_year]':'2026','fields[project_stage]':'development','fields[cover_image]':'0'};
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(nativeValues)});
 ok(r.status===302 && JSON.parse(cli('content-fixture.php','get',content.id)).fields.location==='Native HTTP changed','native editor HTTP save persists custom fields');
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...nativeValues,'fields[location]':'Stale HTTP attempt'})});
 ok(r.status===409 && JSON.parse(cli('content-fixture.php','get',content.id)).fields.location==='Native HTTP changed','stale native HTTP whole save refused');
 const beforePublish=JSON.parse(cli('content-fixture.php','get',content.id));
 const freshForm=await editor(formPath);
 const freshValues={...nativeValues,fwf_meta_revision:freshForm.body.match(/name="fwf_meta_revision" value="([^"]+)"/)?.[1],fwf_content_revision:freshForm.body.match(/name="fwf_content_revision" value="([^"]+)"/)?.[1]};
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...freshValues,post_title:'Invalid publish must not save',content:'Invalid body must not save',post_status:'publish','fields[project_year]':'9999'})});
 ok(r.status===400 && JSON.parse(cli('content-fixture.php','get',content.id)).revision===beforePublish.revision,'invalid native HTTP publish preserves title body status and fields');
 const missingNonce={...freshValues,post_title:'Missing nonce must not save',post_status:'publish'};delete missingNonce.fwf_fields_nonce;
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(missingNonce)});
 ok(r.status===403 && JSON.parse(cli('content-fixture.php','get',content.id)).revision===beforePublish.revision,'missing field nonce blocks whole native HTTP publish');
 const malformed={...freshValues,post_status:'publish',fields:'invalid'};for(const key of Object.keys(malformed)){if(key.startsWith('fields[')){delete malformed[key];}}
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(malformed)});
 ok(r.status===400 && JSON.parse(cli('content-fixture.php','get',content.id)).revision===beforePublish.revision,'malformed field payload blocks whole native HTTP write');
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...nativeValues,post_title:'Stale publish must not save',post_status:'publish'})});
 ok(r.status===409 && JSON.parse(cli('content-fixture.php','get',content.id)).revision===beforePublish.revision,'stale native HTTP publish cannot change title or status');
 r=await editor('/wp-admin/post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...freshValues,post_status:'publish'})});
 ok(r.status===302 && JSON.parse(cli('content-fixture.php','get',content.id)).status==='publish','valid native HTTP publish saves through guarded chain');
 const builder=await admin('/wp-admin/admin.php?page=falcon-wf-content');
 ok(builder.body.includes('Content Builder') && builder.body.includes('Field Groups') && !builder.body.includes('Schema dikelola melalui kode'),'builder replaces fixed directory');
 const create=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=types&new=1');
 ok(create.body.includes('Seperti Pages') && create.body.includes('name="revision"'),'new type offers model and conflict revision');
 r=await editor('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'types',key:'fwf_unauthorized'})});ok(r.status===403,'editor definition mutation denied');
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'types',key:'fwf_bad_nonce'})});ok(r.status===403,'builder missing nonce denied');
 const builderNonce=create.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];
 const builderRevision=create.body.match(/name="revision" value="([^"]+)"/)?.[1];
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'types',key:'fwf_http_type',label:'HTTP Type Fixture',slug:'http-type-fixture',model:'page',active:'1',revision:builderRevision,_wpnonce:builderNonce})});
 ok(r.status===302,'administrator creates type through builder HTTP boundary');
 const typeList=await admin('/wp-admin/admin.php?page=falcon-wf-content');ok(typeList.body.includes('HTTP Type Fixture') && typeList.body.includes('fwf_http_type'),'created definition and native menu appear');
 const newGroup=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=groups&new=1');
 const groupNonce=newGroup.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];const groupRevision=newGroup.body.match(/name="revision" value="([^"]+)"/)?.[1];
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'groups',key:'http_fields',label:'HTTP Fields Fixture',active:'1',revision:groupRevision,_wpnonce:groupNonce,'types[0]':'post','types[1]':'page','types[2]':'fwf_http_type','fields[0][key]':'http_extra_note','fields[0][label]':'HTTP Extra Note','fields[0][kind]':'text','fields[0][default]':''})});
 ok(r.status===302,'administrator creates field group through HTTP boundary');
 const groupList=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=groups');ok(groupList.body.includes('HTTP Fields Fixture'),'created field group persists');
 const fieldForm=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=groups&key=project_details');
 ok(fieldForm.body.includes('Field Type') && fieldForm.body.includes('data-add-field') && fieldForm.body.includes('project_year'),'ACF style field rows render');
 const navigation=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=navigation');
 ok(navigation.body.includes('fwf-menu-row') && navigation.body.includes('Reset urutan bawaan'),'navigation reorder and reset render');
 const listing=await admin('/wp-admin/admin.php?page=falcon-wf-content&tab=listing');
 const termNonce=listing.body.match(/data-nonce="([^"]+)"/)?.[1];
 const requestTerms=(client,values)=>client('/wp-admin/admin-ajax.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_listing_terms',type:'post',taxonomy:'category',nonce:termNonce,...values})});
 let termResponse=await requestTerms(admin,{});ok(termResponse.status===200 && Array.isArray(JSON.parse(termResponse.body).data.terms),'listing loads registered taxonomy terms');
 termResponse=await requestTerms(admin,{nonce:'invalid'});ok(termResponse.status===403,'listing terms require valid nonce');
 termResponse=await requestTerms(editor,{});ok(termResponse.status===403,'editor cannot access builder terms endpoint');
 termResponse=await requestTerms(admin,{type:'page'});ok(termResponse.status===400,'listing rejects taxonomy unrelated to type');
 const navNonce=navigation.body.match(/name="_wpnonce" value="([^"]+)"/)?.[1];
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'navigation',_wpnonce:navNonce,'order[0]':'edit.php?post_type=fwf_project','order[1]':'edit.php?post_type=page'})});
 const reordered=await admin('/wp-admin/admin.php?page=falcon-wf-content');ok(reordered.body.indexOf('id="menu-posts-fwf_project"')<reordered.body.indexOf('id="menu-pages"'),'saved navigation order applied to native menu');
 r=await admin('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_builder',section:'navigation',_wpnonce:navNonce,reset:'1'})});
 const resetMenu=await admin('/wp-admin/admin.php?page=falcon-wf-content');ok(resetMenu.body.indexOf('id="menu-pages"')<resetMenu.body.indexOf('id="menu-posts-fwf_project"'),'navigation reset restores Project after Pages');
 const overview=await admin('/wp-admin/admin.php?page=falcon-wf');
 ok(overview.body.match(/class="wrap fwf"/g)?.length===1 && overview.body.includes('1 · Periksa dan pasang') && overview.body.includes('2 · Pilih theme aktif') && overview.body.includes('3 · Identitas dan konten'),'setup steps reflect actual theme state');
 console.log(`Admin HTTP checks passed: ${checks}. Visual browser review is separate.`);
}finally{try{cli('builder-fixture.php','restore');cli('content-fixture.php','cleanup',content.id);}finally{cli('cleanup-admin.php',...Object.values(fixtures).map(x=>x.id));}}
