import {spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const owner=randomUUID(),base='http://localhost:8091';
function cli(file,...args){const r=spawnSync('docker',['compose','--env-file','local/.env','-f','local/compose.yml','run','--rm','cli','wp','eval-file',`/fwf-tests/${file}`,...args],{encoding:'utf8'});if(r.status!==0)throw Error('Backup HTTP fixture failed (credentials hidden)');return r.stdout.trim();}
const fixtures=JSON.parse(cli('create-admin.php'));let captured=false,checks=0;
const cookies=new Map();
async function request(path,options={}){const response=await fetch(base+path,{...options,redirect:'manual',headers:{Connection:'close',Cookie:[...cookies].map(([k,v])=>`${k}=${v}`).join('; '),...options.headers}});for(const line of response.headers.getSetCookie()){const part=line.split(';')[0],i=part.indexOf('=');cookies.set(part.slice(0,i),part.slice(i+1));}return response;}
const post=body=>request('/wp-admin/admin-post.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});
const ok=(value,name)=>{assert(value,name);checks++;console.log('PASS:',name);};
const ids=html=>new Set([...html.matchAll(/name="backup_id" value="([a-f0-9-]{36})"/g)].map(m=>m[1]));
const nonce=(html,op)=>html.match(new RegExp(`name="operation" value="${op}"[\\s\\S]*?name="_wpnonce" value="([^"]+)"`))?.[1];
const screen=async()=>await(await request('/wp-admin/admin.php?page=falcon-wf-backup')).text();
try {
 const mediaFixture=JSON.parse(cli('backup-http.php','capture',owner));captured=true;
 await request('/wp-login.php');const login=await request('/wp-login.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({log:fixtures.administrator.login,pwd:fixtures.administrator.password,testcookie:'1',redirect_to:base+'/wp-admin/'})});ok(login.status===302,'backup administrator fixture login');
 const identity=await(await request('/wp-admin/admin.php?page=falcon-wf-identity')).text();const identityNonce=nonce(identity,'save_identity');
 const setIdentity=async suffix=>{const r=await post({action:'fwf_action',operation:'save_identity',screen:'identity',name:`FWF HTTP ${owner} ${suffix}`,contact:'',_wpnonce:identityNonce});assert.equal(r.status,302);await r.text();};
 await setIdentity('before');let html=await screen();const before=ids(html);
 const scheduleSection=html.match(/<section class="fwf-panel"><h2>Backup berkala[\s\S]*?<\/section>/)[0];const scheduleRevision=scheduleSection.match(/name="revision" value="([^"]+)"/)[1];
 let savedSchedule=await post({action:'fwf_action',operation:'save_backup_schedule',screen:'backup',frequency:'weekly',weekday:'3',time:'04:25','scheduled_components[]':'settings',revision:scheduleRevision,_wpnonce:nonce(scheduleSection,'save_backup_schedule')});await savedSchedule.text();html=await screen();
 let savedSection=html.match(/<section class="fwf-panel"><h2>Backup berkala[\s\S]*?<\/section>/)[0];ok(savedSchedule.status===302 && savedSection.includes('value="04:25"') && /value="weekly"[^>]*selected/.test(savedSection) && savedSection.includes('Belum aktif / belum terjadwal'),'actual HTTP schedule save persists fields while keeping automatic jobs disabled');
 savedSchedule=await post({action:'fwf_action',operation:'save_backup_schedule',screen:'backup',frequency:'daily',weekday:'1',time:'05:30','scheduled_components[]':'settings',revision:scheduleRevision,_wpnonce:nonce(savedSection,'save_backup_schedule')});await savedSchedule.text();html=await screen();savedSection=html.match(/<section class="fwf-panel"><h2>Backup berkala[\s\S]*?<\/section>/)[0];ok(savedSection.includes('value="04:25"') && !savedSection.includes('value="05:30"'),'stale HTTP schedule form cannot overwrite saved configuration');

 const mediaNonce=html.match(/data-fwf-media-picker[^>]*data-nonce="([^"]+)"/)?.[1];assert(mediaNonce,'media picker nonce');
 const preview=async values=>request('/wp-admin/admin-ajax.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({action:'fwf_backup_media',_ajax_nonce:mediaNonce,ids:String(mediaFixture.media_id),...values})});
 let mediaResponse=await preview({_ajax_nonce:'invalid'});await mediaResponse.text();ok(mediaResponse.status===403,'selected media estimate requires dedicated nonce');
 mediaResponse=await preview({});const estimate=await mediaResponse.json();ok(mediaResponse.status===200 && estimate.success && estimate.data.files===1 && estimate.data.attachments===1 && estimate.data.bytes>17,'actual AJAX selected estimate resolves file and attachment metadata');
 mediaResponse=await preview({ids:'../1'});await mediaResponse.text();ok(mediaResponse.status===400,'actual AJAX rejects malformed selected IDs');
 const mediaBefore=ids(html);const mediaPost=await post({action:'fwf_action',operation:'create_backup',screen:'backup','components[]':'media',manual_media_mode:'selected',manual_media_ids:String(mediaFixture.media_id),_wpnonce:nonce(html,'create_backup')});await mediaPost.text();html=await screen();const mediaJob=[...html.matchAll(/data-job-id="([a-f0-9-]{36})"/g)].map(m=>m[1]).find(id=>!mediaBefore.has(id));assert(mediaJob);cli('backup-http.php','runjob',owner,mediaJob);html=await screen();ok(mediaPost.status===302 && ids(html).has(mediaJob),'actual HTTP selected media form produces scoped ZIP through existing worker');

 let response=await post({action:'fwf_action',operation:'create_backup',screen:'backup','components[]':'settings',backup_note:'Sebelum revisi desain',_wpnonce:nonce(html,'create_backup')});await response.text();html=await screen();
 const queued=[...html.matchAll(/data-job-id="([a-f0-9-]{36})"/g)].map(m=>m[1]).find(id=>!before.has(id) && id!==mediaJob);assert(queued,'queued job shown');cli('backup-http.php','runjob',owner,queued);html=await screen();
 const created=[...ids(html)].find(id=>!before.has(id) && id!==mediaJob);ok(response.status===302 && !!created,'actual dashboard queues worker and creates settings ZIP');
 ok(html.includes('Sebelum revisi desain') && html.includes('fwf-backup-summary') && html.includes('value="Restore"') && html.includes('value="Delete"'),'archive card renders notes, two-line summary and Restore/Delete buttons');
 const card=html.match(new RegExp('data-backup-id="'+created+'"[\\s\\S]*?</section>'))[0];
 response=await post({action:'fwf_action',operation:'save_backup_note',screen:'backup',backup_id:created,backup_note:'<script>alert(1)</script> Catatan klien baru',_wpnonce:nonce(card,'save_backup_note')});await response.text();html=await screen();ok(response.status===302 && html.includes('Catatan klien baru') && !html.includes('<script>alert(1)</script>'),'actual HTTP note save sanitizes text before escaped rendering');
 response=await post({action:'fwf_action',operation:'protect_backup',screen:'backup',backup_id:created,_wpnonce:nonce(html,'protect_backup')});await response.text();html=await screen();
 const protectedCard=html.match(new RegExp('data-backup-id="'+created+'"[\\s\\S]*?</section>'))[0];ok(response.status===302 && protectedCard.includes('🔒 Terlindungi') && protectedCard.includes('Lepas Perlindungan') && protectedCard.includes('disabled'),'HTTP protection renders lock, reverse action and disabled Delete');
 response=await post({action:'fwf_action',operation:'unprotect_backup',screen:'backup',backup_id:created,_wpnonce:nonce(protectedCard,'unprotect_backup')});await response.text();html=await screen();
 const releasedCard=html.match(new RegExp('data-backup-id="'+created+'"[\\s\\S]*?</section>'))[0];ok(response.status===302 && releasedCard.includes('Lindungi backup ini') && !releasedCard.includes('🔒 Terlindungi'),'HTTP unprotect restores original action');
 response=await post({action:'fwf_action',operation:'download_backup',screen:'backup',backup_id:created,_wpnonce:nonce(html,'download_backup')});const bytes=await response.arrayBuffer();
 ok(response.status===200 && response.headers.get('content-type')==='application/zip' && new Uint8Array(bytes)[0]===80 && response.headers.get('cache-control')?.includes('no-cache'),'authenticated download streams private ZIP without caching');
 const denied=await fetch(base+`/fwf-backups/${created}.zip`,{headers:{Connection:'close'}});const publicBytes=new Uint8Array(await denied.arrayBuffer());ok(denied.headers.get('content-type')!=='application/zip' && !(publicBytes[0]===80 && publicBytes[1]===75),'public URL does not expose private ZIP even through WordPress canonical redirects');
 const anonymous=await fetch(base+`/wp-admin/admin-post.php?action=fwf_action&operation=download_backup&backup_id=${created}`,{headers:{Connection:'close'}});const anonymousBytes=new Uint8Array(await anonymous.arrayBuffer());ok(anonymous.headers.get('content-type')!=='application/zip' && !(anonymousBytes[0]===80 && anonymousBytes[1]===75),'anonymous caller cannot stream private backup');
 const journal=JSON.parse(cli('backup-http.php','makejournal',owner,created)).journal;html=await screen();response=await post({action:'fwf_action',operation:'review_recovery',screen:'backup',journal_id:journal,_wpnonce:nonce(html,'review_recovery')});await response.text();html=await screen();ok(response.status===302 && html.includes('Review pemulihan terputus') && html.includes('Database belum commit'),'actual HTTP recovery review shows commit-based action and confirmation');
 response=await post({action:'fwf_action',operation:'apply_recovery',screen:'backup',journal_id:journal,_wpnonce:nonce(html,'apply_recovery')});await response.text();html=await screen();ok(html.includes(journal),'missing HTTP recovery confirmation preserves owned empty journal');response=await post({action:'fwf_action',operation:'review_recovery',screen:'backup',journal_id:journal,_wpnonce:nonce(html,'review_recovery')});await response.text();html=await screen();response=await post({action:'fwf_action',operation:'apply_recovery',screen:'backup',journal_id:journal,confirm:'yes',_wpnonce:nonce(html,'apply_recovery')});await response.text();html=await screen();ok(response.status===302 && !html.includes(journal) && html.includes('Tidak ada restore terputus'),'confirmed HTTP recovery resolves only its owned empty journal');
 const form=new FormData();form.set('action','fwf_action');form.set('operation','import_backup');form.set('screen','backup');form.set('_wpnonce',nonce(html,'import_backup'));form.set('backup_file',new Blob([bytes],{type:'application/zip'}),'backup.zip');
 const previous=ids(html);response=await request('/wp-admin/admin-post.php',{method:'POST',body:form});await response.text();html=await screen();const imported=[...ids(html)].find(id=>!previous.has(id));ok(response.status===302 && !!imported,'actual multipart local ZIP upload validates and imports');
 await setIdentity('after');response=await post({action:'fwf_action',operation:'review_backup',screen:'backup',backup_id:imported,_wpnonce:nonce(html,'review_backup')});await response.text();html=await screen();ok(response.status===302 && html.includes('Review pemulihan') && html.includes('name="confirm"'),'review displays explicit restore confirmation');
 const prior=ids(html);response=await post({action:'fwf_action',operation:'restore_backup',screen:'backup',backup_id:imported,confirm:'yes',_wpnonce:nonce(html,'restore_backup')});await response.text();html=await screen();
 const restored=await(await request('/wp-admin/admin.php?page=falcon-wf-identity')).text();ok(response.status===302 && restored.includes(`FWF HTTP ${owner} before`) && [...ids(html)].some(id=>!prior.has(id)),'actual reviewed HTTP restore recovers identity and creates safety ZIP');
 response=await post({action:'fwf_action',operation:'restore_backup',screen:'backup',backup_id:imported,confirm:'yes',_wpnonce:nonce(html,'create_backup')});ok(response.status===403,'restore cannot reuse a different action nonce');await response.text();
 const deleteCard=html.match(new RegExp('data-backup-id="'+created+'"[\\s\\S]*?</section>'))[0];
 response=await post({action:'fwf_action',operation:'review_delete_backup',screen:'backup',backup_id:created,_wpnonce:nonce(deleteCard,'review_delete_backup')});await response.text();html=await screen();ok(response.status===302 && html.includes('Konfirmasi Delete') && html.includes('Hapus permanen file backup ini.'),'Delete opens selected archive review without deleting');
 response=await post({action:'fwf_action',operation:'delete_backup',screen:'backup',backup_id:created,_wpnonce:nonce(html,'delete_backup')});await response.text();html=await screen();ok(ids(html).has(created),'missing delete confirmation preserves selected archive');
 response=await post({action:'fwf_action',operation:'review_delete_backup',screen:'backup',backup_id:created,_wpnonce:nonce(html,'review_delete_backup')});await response.text();html=await screen();
 response=await post({action:'fwf_action',operation:'delete_backup',screen:'backup',backup_id:created,confirm:'yes',_wpnonce:nonce(html,'delete_backup')});await response.text();html=await screen();ok(response.status===302 && !ids(html).has(created) && ids(html).has(imported),'confirmed HTTP deletion removes selected ZIP while retaining other archives');
 console.log(`Backup HTTP checks passed: ${checks}. Local fixture only.`);
} finally {try{if(captured)cli('backup-http.php','cleanup',owner);}finally{cli('cleanup-admin.php',...Object.values(fixtures).map(v=>String(v.id)));}}
