<?php
use FalconWF\Backup\Manager as B;
use FalconWF\Backup\MediaSelection as M;
use FalconWF\Backup\Scheduler as S;
if(wp_get_environment_type()!=='local'||FWF_BACKUP_DIR!=='/fwf-backups/media-test-'.getenv('FWF_MEDIA_TEST_OWNER'))throw new RuntimeException('Isolated fixture required.');
global $wpdb;$original=$wpdb->prefix;$prefix='fwbt_'.bin2hex(random_bytes(5)).'_';$tables=[];$folder=null;$count=0;
$ok=static function($value,$label)use(&$count){if(!$value)throw new RuntimeException('FAIL: '.$label);echo "PASS: $label\n";$count++;};$must=static function($value){if(is_wp_error($value))throw new RuntimeException($value->get_error_message());return $value;};
wp_set_current_user(get_user_by('login','fwf-admin')->ID);
try{
 foreach($wpdb->get_col($wpdb->prepare('SHOW TABLES LIKE %s',$wpdb->esc_like($original).'%')) as $source){$target=$prefix.substr($source,strlen($original));if($wpdb->query("CREATE TABLE `$target` LIKE `$source`")===false)throw new RuntimeException('Clone failed.');$tables[]=$target;if($wpdb->query("INSERT INTO `$target` SELECT * FROM `$source`")===false)throw new RuntimeException('Rows failed.');}
 $wpdb->set_prefix($prefix);wp_cache_flush();delete_option('fwf_backup_schedule');delete_option('fwf_backup_schedule_state');delete_option('fwf_backup_schedule_runs');delete_option('fwf_backup_retention');
 $upload=wp_get_upload_dir();$relative='fwf-media-fixture-'.wp_generate_uuid4();$folder=$upload['basedir'].'/'.$relative;wp_mkdir_p($folder);
 foreach(['report.pdf'=>'REPORT ORIGINAL','photo-scaled.jpg'=>'SCALED','photo.jpg'=>'ORIGINAL','thumb.jpg'=>'THUMB','old-edit.jpg'=>'EDIT','other.pdf'=>'UNSELECTED','cover.jpg'=>'COVER'] as $name=>$bytes)file_put_contents($folder.'/'.$name,$bytes);
 $attach=static function($name)use($relative,$folder){$id=wp_insert_attachment(['post_title'=>$name,'post_mime_type'=>str_ends_with($name,'.pdf')?'application/pdf':'image/jpeg','guid'=>home_url('/uploads/'.$relative.'/'.$name)],$folder.'/'.$name,0,true);if(is_wp_error($id))throw new RuntimeException($id->get_error_message());update_post_meta($id,'_wp_attached_file',$relative.'/'.$name);return $id;};
 $report=$attach('report.pdf');$image=$attach('photo-scaled.jpg');$other=$attach('other.pdf');$cover=$attach('cover.jpg');update_post_meta($report,'_thumbnail_id',(string)$cover);$wpdb->update($wpdb->posts,['post_parent'=>$report],['ID'=>$cover]);
 update_post_meta($image,'_wp_attachment_metadata',['file'=>$relative.'/photo-scaled.jpg','original_image'=>'photo.jpg','sizes'=>['thumbnail'=>['file'=>'thumb.jpg','width'=>100,'height'=>100]]]);update_post_meta($image,'_wp_attachment_backup_sizes',['full-orig'=>['file'=>'old-edit.jpg']]);update_post_meta($image,'_wp_attachment_image_alt','Old alt');update_post_meta($image,'plugin_custom','PRESERVE');
 $ids=M::ids([$image,$report]);$snapshot=M::snapshot($ids);$ok($snapshot['count']===6 && count($snapshot['records'])===3,'selected records include PDF, image variants, original, edit backup and cover dependency');
 $names=array_keys($snapshot['files']);$ok(!in_array('media/'.$relative.'/other.pdf',$names),'unselected report excluded');
 $ok($must(B::estimates($ids))['media']['bytes']===$snapshot['bytes'],'selection estimate includes file and attachment metadata bytes');
 foreach([[],[$image,$image],['../1'],[true],['0']] as $bad){try{M::ids($bad);$rejected=false;}catch(Throwable $e){$rejected=true;}$ok($rejected,'invalid selection rejected '.wp_json_encode($bad));}
 $ok(is_wp_error(B::queue(['database','media'],false,'',$ids)) && is_wp_error(B::queue(['settings'],false,'',$ids)),'selected media rejects whole database and missing media component');
 $backup=$must(B::create(['media'],$ids));$review=$must(B::inspect($backup));$ok($review['manifest']['media_selection']===$ids && $review['manifest']['schema']===3,'signed manifest records selected roots and schema');
 $ok(count(array_filter(array_keys($review['manifest']['entries']),static fn($entry)=>str_starts_with($entry,'files/media/')))===6,'ZIP exact media closure inventory');
 file_put_contents($folder.'/photo.jpg','CHANGED');update_post_meta($image,'_wp_attachment_image_alt','New alt');$review=$must(B::inspect($backup));file_put_contents($folder.'/other.pdf','LIVE OTHER');$ok(is_wp_error(B::restore($backup,$review['sha256'],$review['revision'],true)),'concurrent live change invalidates selected restore review');
 $review=$must(B::inspect($backup));$before=count(B::listing());$must(B::restore($backup,$review['sha256'],$review['revision'],true));$ok(file_get_contents($folder.'/photo.jpg')==='ORIGINAL' && get_post_meta($image,'_wp_attachment_image_alt',true)==='Old alt','selected restore recovers files and canonical attachment metadata');
 $ok(file_get_contents($folder.'/other.pdf')==='LIVE OTHER' && get_post_meta($image,'plugin_custom',true)==='PRESERVE','unselected files and plugin metadata retained');$ok(count(B::listing())===$before+1,'selected restore creates full database/uploads safety archive');
 // Metadata SQL fault after file overlay must roll back both dimensions.
 file_put_contents($folder.'/photo.jpg','ROLLBACK');update_post_meta($image,'_wp_attachment_image_alt','Rollback alt');$review=$must(B::inspect($backup));$fail=static function($query)use($wpdb){return str_starts_with($query,"INSERT INTO `$wpdb->postmeta`")?'INSERT INTO `fwf_missing_table` VALUES(1)':$query;};$quiet=$wpdb->suppress_errors(true);add_filter('query',$fail);$result=B::restore($backup,$review['sha256'],$review['revision'],true);remove_filter('query',$fail);$wpdb->suppress_errors($quiet);wp_cache_flush();$ok(is_wp_error($result) && file_get_contents($folder.'/photo.jpg')==='ROLLBACK' && get_post_meta($image,'_wp_attachment_image_alt',true)==='Rollback alt','scoped metadata SQL failure rolls back attachment and file writes');
 $wpdb->delete($wpdb->postmeta,['post_id'=>$report]);$wpdb->delete($wpdb->posts,['ID'=>$report]);unlink($folder.'/report.pdf');wp_cache_flush();$review=$must(B::inspect($backup));$must(B::restore($backup,$review['sha256'],$review['revision'],true));$ok(get_post($report)->post_type==='attachment' && file_get_contents($folder.'/report.pdf')==='REPORT ORIGINAL','deleted selected attachment and cover-parent link restored with original IDs');
 $originalMeta=get_post_meta($image,'_wp_attachment_metadata',true);update_post_meta($image,'_wp_attachment_metadata',['file'=>$relative.'/photo-scaled.jpg','sizes'=>['bad'=>['file'=>'../other.pdf']]]);$ok(is_wp_error(B::create(['media'],[$image])),'metadata traversal rejected before snapshot');update_post_meta($image,'_wp_attachment_metadata',$originalMeta);unlink($folder.'/thumb.jpg');$ok(is_wp_error(B::create(['media'],[$image])),'missing declared variant fails clearly instead of incomplete backup');file_put_contents($folder.'/thumb.jpg','THUMB');
 update_post_meta($other,'_wp_attached_file',$relative.'/photo.jpg');$ok(is_wp_error(B::create(['media'],[$image])) && is_wp_error(B::inspect($backup)),'shared path outside selected attachments blocks backup and restore review');update_post_meta($other,'_wp_attached_file',$relative.'/other.pdf');
 $wpdb->update($wpdb->posts,['post_type'=>'page'],['ID'=>$report]);$ok(is_wp_error(B::inspect($backup)),'attachment ID reused by other content blocks restore review');$wpdb->update($wpdb->posts,['post_type'=>'attachment'],['ID'=>$report]);
 $wpdb->update($wpdb->postmeta,['meta_value'=>'a:1:{s:4:"self";R:1;}'],['post_id'=>$image,'meta_key'=>'_wp_attachment_metadata']);wp_cache_flush();$ok(is_wp_error(B::create(['media'],[$image])),'recursive serialized metadata fails with bounded traversal');update_post_meta($image,'_wp_attachment_metadata',$originalMeta);
 $policy=['enabled'=>true,'frequency'=>'daily','weekday'=>'1','time'=>'02:00','components'=>['media'],'media_selection'=>[$report]];$must(S::save($policy,S::revision()));$state=get_option('fwf_backup_schedule_state');$state['next']=time()-60;update_option('fwf_backup_schedule_state',$state,false);do_action(S::HOOK,S::policy()['generation'],$state['next']);$run=S::runs()[0];$ok($must(B::jobs())[$run['job']]['phase']==='queued','scheduler queues persisted media selection');for($i=0;$i<12;$i++){$job=$must(B::work($run['job']));if($job['phase']==='done')break;}$ok($must(B::inspect($run['job']))['manifest']['media_selection']===[$report],'scheduled archive retains exact selected root');
 $deny=static function($caps){$caps['fwf_manage_system']=false;return $caps;};add_filter('user_has_cap',$deny);$ok(is_wp_error(B::create(['media'],$ids)),'selected backup retains system capability boundary');remove_filter('user_has_cap',$deny);
 echo "Selected media checks passed: $count. Isolated tables/files/archive directory.\n";
}finally{
 if(isset($deny))remove_filter('user_has_cap',$deny);$wpdb->set_prefix($original);wp_cache_flush();wp_set_current_user(0);wp_set_current_user(get_user_by('login','fwf-admin')->ID);foreach($must(B::jobs()) as $id=>$job){B::forget($id);}foreach(glob(FWF_BACKUP_DIR.'/*.zip')?:[] as $file)unlink($file);foreach(['.backup.lock','.backup_schedule.lock','.recovery-key'] as $file)if(is_file(FWF_BACKUP_DIR.'/'.$file))unlink(FWF_BACKUP_DIR.'/'.$file);if(!rmdir(FWF_BACKUP_DIR))throw new RuntimeException('Archive fixture cleanup failed.');
 if($folder){foreach(glob($folder.'/*')?:[] as $file)unlink($file);rmdir($folder);}foreach($tables as $table)$wpdb->query("DROP TABLE `$table`");$wpdb->set_prefix($original);wp_cache_flush();
}
