import {readFileSync, writeFileSync, mkdirSync, rmSync, lstatSync, readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
process.chdir(fileURLToPath(new URL('../',import.meta.url)));
const args=process.argv.slice(2);
assert(args.length===0 || (args.length===4 && args[0]==='--source' && args[2]==='--output'),'Use --source <project directory> --output <artifact directory>');
const source=args.length?path.resolve(args[1]):'examples/projects/falcon-reference';
const spec=JSON.parse(readFileSync(`${source}/project.json`));
assert.equal(spec.schema,1);assert.match(spec.project_id,/^[a-z][a-z0-9-]{0,63}$/);assert(!['falcon-wf','falcon-theme'].includes(spec.project_id));
assert.equal(spec.package.id,spec.project_id);assert.equal(spec.package.type,'theme');assert.equal(spec.package.parent,'falcon-theme');
assert.match(spec.version,/^\d+\.\d+\.\d+-(alpha|beta|rc)\.[1-9]\d*$/);assert.equal(spec.status,'development');
assert(Array.isArray(spec.runtime) && new Set(spec.runtime).size===spec.runtime.length);
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const build=`build/projects/${spec.project_id}`,output=args.length?path.resolve(args[3]):'dist/projects';
const sourceRoot=path.resolve(source),outputRoot=path.resolve(output);
assert(outputRoot!==sourceRoot && !outputRoot.startsWith(sourceRoot+path.sep),'Output must be outside project source');
const buildRoot=path.resolve(build);
const overlaps=(a,b)=>a===b || a.startsWith(b+path.sep) || b.startsWith(a+path.sep);
assert(!overlaps(sourceRoot,buildRoot) && !overlaps(outputRoot,buildRoot),'Source/output must not overlap generated build');
rmSync(build,{recursive:true,force:true});mkdirSync(build,{recursive:true});mkdirSync(output,{recursive:true});
const inputs=[{source:`${source}/project.json`,sha256:hash(readFileSync(`${source}/project.json`))}];
for(const relative of spec.runtime){
 assert(typeof relative==='string' && !path.isAbsolute(relative) && !relative.includes('..') && !relative.includes('\\'));
 assert(/\.(php|css)$/.test(relative));const file=path.join(source,relative);
 let checked=sourceRoot;assert(!lstatSync(checked).isSymbolicLink());for(const part of relative.split('/')){checked=path.join(checked,part);assert(!lstatSync(checked).isSymbolicLink(),'Symlink runtime source refused');}
 assert(lstatSync(file).isFile());
 const original=readFileSync(file);let bytes=original.toString('utf8').replaceAll('@@PROJECT_VERSION@@',spec.version);assert(!bytes.includes('@@PROJECT_'));
 const target=path.join(build,relative);mkdirSync(path.dirname(target),{recursive:true});writeFileSync(target,bytes);
 inputs.push({source:file,path:relative,sha256:hash(original)});
}
const walk=folder=>readdirSync(folder,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(folder,e.name)):[path.join(folder,e.name)]);
const runtime=walk(source).filter(file=>/\.(php|css)$/.test(file)).map(file=>path.relative(source,file));
assert.deepEqual(runtime.sort(),[...spec.runtime].sort(),'All runtime sources must be mapped');
const style=readFileSync(`${build}/style.css`,'utf8');assert(style.includes(`Template: ${spec.package.parent}`) && style.includes(`Version: ${spec.version}`));
const artifact=`${spec.package.id}-${spec.version}.zip`;
const zipped=spawnSync('python3',['scripts/zip.py',build,`${output}/${artifact}`,spec.package.id],{stdio:'inherit'});if(zipped.status!==0)throw Error('Project ZIP failed');
const git=argv=>spawnSync('git',argv,{encoding:'utf8',cwd:sourceRoot});
const commit=git(['rev-parse','HEAD']),dirty=git(['status','--porcelain']);
const tracked=git(['ls-files','--error-unmatch','project.json',...spec.runtime]);
const clean=commit.status===0 && dirty.status===0 && !dirty.stdout.trim() && tracked.status===0;
const manifest={schema:1,project_id:spec.project_id,version:spec.version,status:spec.status,source_commit:commit.status===0 && tracked.status===0?commit.stdout.trim():null,dirty:!clean,source_digest:hash(JSON.stringify(inputs)),packages:[{...spec.package,version:spec.version,artifact,sha256:hash(readFileSync(`${output}/${artifact}`)),min_wp:spec.min_wp,min_php:spec.min_php,compatibility:spec.compatibility}]};
writeFileSync(`${output}/project-manifest.json`,JSON.stringify(manifest,null,2)+'\n');
writeFileSync(`${output}/build-report.json`,JSON.stringify({inputs,acceptance:'Local reference only; live client/private distribution acceptance pending.'},null,2)+'\n');
console.log(`Built project: ${output}/${artifact}`);
